apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nifi-role-binding
subjects:
  - kind: ServiceAccount
    name: nifi-sa
    namespace: nifi
roleRef:
  kind: ClusterRole
  name: nifi-role
  apiGroup: rbac.authorization.k8s.io