apiVersion: v1
kind: Namespace
metadata:
  name: nifi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifi-sa
  namespace: nifi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifi-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nifi-role-binding
subjects:
  - kind: ServiceAccount
    name: nifi-sa
    namespace: nifi
roleRef:
  kind: ClusterRole
  name: nifi-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  namespace: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      serviceAccountName: nifi-sa
      containers:
        - name: nifi
          image: apache/nifi:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  namespace: nifi
spec:
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
